server:
  host: '127.0.0.1'
  port: 1234
  https:
    enabled: false
    certificate: '/absolute/path/to.crt'
    private_key: '/absolute/path/to.key'

database:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'aoc1080p'
  database: 'coattail'