paths:
  root: "{root}"
  actions: "{root}/actions/"
  receivers: "{root}/receivers/"

service:
  # TLS Configuration
  tls:
    # TLS is not yet supported in Coattail.
    use_tls: false
  # The local address and port to bind to.
  network:
    address:
      # The address that other peers should use to connect to this instance.
      connection: "127.0.0.1"
      # The address that this peer should bind to when setting up it's server.
      bind: "127.0.0.1"
    # The port to use.
    port: 49365
  # The session ID factory to use, can be either `uuid` or `incremental`.
  session_id_factory: 'uuid'
  log: "{root}/service.log"

authentication:
  private_key:
    type: "file"
    value: "{root}/keys/auth-key.pem"
  public_key:
    type: "file"
    value: "{root}/keys/auth-key.pub"

validation:
  private_key:
    type: "file"
    value: "{root}/keys/vt-key.pem"
  public_key:
    type: "file"
    value: "{root}/keys/vt-key.pub"

data:
  client: "sqlite3"
  connection:
    filename: "{dbfile}"
  migrations:
    directory: "{install}/lib/data/migrations"
    tableName: "knex_migrations"
