paths:
  root: {root}
  actions: {actions}
  receivers: {receivers}

service:
  # TLS Configuration
  tls:
    enabled: false
    key: /absolute/path/to/key.pem
    cert: /absolute/path/to/cert.pem
  # The local address and port to bind to.
  network:
    address:
      # The address that other peers should use to connect to this instance.
      connection: "127.0.0.1"
      # The address that this peer should bind to when setting up it's server.
      bind: "127.0.0.1"
    # The port to use.
    port: 49365
  # The session ID factory to use, can be either `uuid` or `incremental`.
  session_id_factory: uuid
  log: {log}

authentication:
  private_key:
    type: file
    value: {auth-key-priv}
  public_key:
    type: file
    value: {auth-key-pub}

validation:
  private_key:
    type: file
    value: {validation-key-priv}
  public_key:
    type: file
    value: {validation-key-pub}

data:
  client: sqlite3
  connection:
    filename: {dbfile}
  migrations:
    directory: {migrations}
    tableName: knex_migrations
