paths:
  root: "{root}"
  actions: "{root}/actions/"
  schemas: "{root}/schemas/"

service:
  # TLS Configuration
  tls:
    use_tls: false
    # tls properties should be identical to those specified here:
    # https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener
  listen:
    # Address must be a valid IPv4 address. Hostnames are not supported.
    address: "127.0.0.1"
    port: 49365
  # How frequently to ask clients to send keep-alive packets.
  keep_alive_interval: 2000
  # The session ID factory to use, can be either `uuid` or `incremental`.
  session_id_factory: 'uuid'
  log: "{root}/service.log"

authentication:
  private_key:
    type: "file"
    value: "{root}/keys/key.pem"
  public_key:
    type: "file"
    value: "{root}/keys/key.pub"

data:
  client: "sqlite3"
  connection:
    filename: "{dbfile}"
  migrations:
    directory: "{install}/lib/data/migrations"
    tableName: "knex_migrations"
